# config/routes.yaml

app_blog:
    path: /blog
    controller: App\Controller\BlogController::index

app_admin:
    path: /admin
    controller: App\Controller\BlogController::indexadmin
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout



app_client:
    path: /client
    controller: App\Controller\BlogController::indexclient
    
app_reset_password:
    path: /reset_password
    controller: App\Controller\SecurityController::resetPassword
    # config/routes.yaml
# config/routes.yaml

# config/routes.yaml

paginate_users:
    path: '/paginate-users'
    controller: App\Controller\UserController::index
    methods: ['POST']

sort_users:
    path: '/sort-users'
    controller: App\Controller\UserController::index
    methods: ['POST']
app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show
    